# Generated by Django 2.2.28 on 2022-07-19 15:29

from django.db import migrations
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_alter_logentry_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='changes',
            field=JSONField(blank=True, verbose_name='change message'),
        ),
    ]
