# Generated by Django 4.0.8 on 2022-11-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0010_alter_logentry_timestamp'),
        ('auditlog', '0010_auto_20220719_1729'),
        ('auditlog', '0011_auto_20221001_1729'),
    ]

    operations = [
    ]
