# Generated by Django 4.0.8 on 2022-11-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0012_add_logentry_action_access'),
        ('auditlog', '0012_merge_20221113_1824'),
    ]

    operations = [
    ]
